apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-scheduler
  namespace: oiler-backup-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-scheduler
  template:
    metadata:
      labels:
        app: mysql-scheduler
    spec:
      serviceAccountName: mysql-scheduler-sa
      containers:
        - name: grpc-server
          image: ashadrinnn/mysqlad:0.0.1-1
          imagePullPolicy: Always
          ports:
            - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-scheduler-service
  namespace: oiler-backup-system
spec:
  selector:
    app: mysql-scheduler
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mysql-scheduler-role
  namespace: oiler-backup-system
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["cronjobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mysql-scheduler-sa
  namespace: oiler-backup-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mysql-scheduler-rolebinding
  namespace: oiler-backup-system
subjects:
  - kind: ServiceAccount
    name: mysql-scheduler-sa
    namespace: oiler-backup-system
roleRef:
  kind: Role
  name: mysql-scheduler-role
  apiGroup: rbac.authorization.k8s.io
