# permissions for end users to edit backuprequests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprequest-editor-role
rules:
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprequests/status
  verbs:
  - get
