# This rule is not used by the project oiler-backup itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over backup.oiler.backup.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprestore-admin-role
rules:
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprestores
  verbs:
  - '*'
- apiGroups:
  - backup.oiler.backup
  resources:
  - backuprestores/status
  verbs:
  - get
