---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - base.oiler.backup
  resources:
  - backuprequests
  - restorerequests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - base.oiler.backup
  resources:
  - backuprequests/finalizers
  - restorerequests/finalizers
  verbs:
  - update
- apiGroups:
  - base.oiler.backup
  resources:
  - backuprequests/status
  - restorerequests/status
  verbs:
  - get
  - patch
  - update
