apiVersion: backup.oiler.backup/v1
kind: BackupRequest
metadata:
  labels:
    app.kubernetes.io/name: oiler-backup
    app.kubernetes.io/managed-by: kustomize
  name: backuprequest-sample
spec:
  dbUri: "10.97.28.234"
  databasePort: 3306
  databaseUser: "root"
  databasePass: "rootpassword"
  databaseName: "testdb"
  databaseType: "mysql"
  schedule: "*/1 * * * *"
  storageClass: "s3"
  s3Endpoint: "https://10.109.113.71:443"
  s3AccessKey: 1W4OP4oW794fr5qtxkfJ
  s3SecretKey: HKjkGyxvJSRcO3taCZZkUrHviFDPGTviAIcj3GLI
  maxBackupCount: 2
  s3BucketName: test
